### ISSUE TITLE
No longer required :)

### ISSUE THREAD

**Issue by dthompsonza** [stephanjohnson/FNB-Copy-Paste-Prevention-Killer#1]
“We note with concern the recommendation to install unauthorised software and browser extensions by some users in a bid to circumvent the auto-filling of passwords,” he said.

“The use of this type of software for your banking is strongly discouraged as it places the user at a high risk of introducing malicious software onto their device.”

https://mybroadband.co.za/news/banking/316921-fnb-reverses-decision-to-block-password-managers.html

**Comment by stephanjohnson** [comment]
Hmmmm, i wonder why i stopped coding on this :)
